/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const Transaction = IDL.Record({
  'id' : IDL.Nat,
  'note' : IDL.Text,
  'recipient' : IDL.Principal,
  'timestamp' : Time,
  'payer' : IDL.Principal,
  'amount' : IDL.Nat,
});
export const UserProfile = IDL.Record({
  'displayName' : IDL.Text,
  'phoneNumber' : IDL.Text,
  'qrCode' : IDL.Text,
});
export const Notification = IDL.Record({
  'id' : IDL.Nat,
  'recipient' : IDL.Principal,
  'isRead' : IDL.Bool,
  'message' : IDL.Text,
  'timestamp' : Time,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createTransaction' : IDL.Func(
      [IDL.Principal, IDL.Nat, IDL.Text],
      [Transaction],
      [],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getNotification' : IDL.Func([IDL.Nat], [Notification], ['query']),
  'getUserNotifications' : IDL.Func([], [IDL.Vec(Notification)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'markNotificationRead' : IDL.Func([IDL.Nat], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveUserProfile' : IDL.Func([UserProfile], [], []),
  'sendQRScanNotification' : IDL.Func([IDL.Principal, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const Transaction = IDL.Record({
    'id' : IDL.Nat,
    'note' : IDL.Text,
    'recipient' : IDL.Principal,
    'timestamp' : Time,
    'payer' : IDL.Principal,
    'amount' : IDL.Nat,
  });
  const UserProfile = IDL.Record({
    'displayName' : IDL.Text,
    'phoneNumber' : IDL.Text,
    'qrCode' : IDL.Text,
  });
  const Notification = IDL.Record({
    'id' : IDL.Nat,
    'recipient' : IDL.Principal,
    'isRead' : IDL.Bool,
    'message' : IDL.Text,
    'timestamp' : Time,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createTransaction' : IDL.Func(
        [IDL.Principal, IDL.Nat, IDL.Text],
        [Transaction],
        [],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getNotification' : IDL.Func([IDL.Nat], [Notification], ['query']),
    'getUserNotifications' : IDL.Func([], [IDL.Vec(Notification)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'markNotificationRead' : IDL.Func([IDL.Nat], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveUserProfile' : IDL.Func([UserProfile], [], []),
    'sendQRScanNotification' : IDL.Func([IDL.Principal, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };